sudo: required
# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: xenial
language: python
python:
  - "3.6"
env:
  - DB=postgres
addons:
    # postgres versions provided by el7 RHSCL (lowest supportable version)
    postgresql: "9.6"
services:
    - postgresql
    - redis-server
install: source .travis/install.sh
before_script: source .travis/before_script.sh
script: source .travis/script.sh
after_failure:
  - sh -c "cat ~/django_runserver.log"
  - sh -c "cat ~/resource_manager.log"
  - sh -c "cat ~/reserved_workers-1.log"
