# coding: utf-8

"""
    Pulp3 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Artifact(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'href': 'str',
        'created': 'datetime',
        'file': 'str',
        'size': 'int',
        'md5': 'str',
        'sha1': 'str',
        'sha224': 'str',
        'sha256': 'str',
        'sha384': 'str',
        'sha512': 'str',
        'upload': 'str'
    }

    attribute_map = {
        'href': '_href',
        'created': '_created',
        'file': 'file',
        'size': 'size',
        'md5': 'md5',
        'sha1': 'sha1',
        'sha224': 'sha224',
        'sha256': 'sha256',
        'sha384': 'sha384',
        'sha512': 'sha512',
        'upload': 'upload'
    }

    def __init__(self, href=None, created=None, file=None, size=None, md5=None, sha1=None, sha224=None, sha256=None, sha384=None, sha512=None, upload=None):  # noqa: E501
        """Artifact - a model defined in Swagger"""  # noqa: E501

        self._href = None
        self._created = None
        self._file = None
        self._size = None
        self._md5 = None
        self._sha1 = None
        self._sha224 = None
        self._sha256 = None
        self._sha384 = None
        self._sha512 = None
        self._upload = None
        self.discriminator = None

        if href is not None:
            self.href = href
        if created is not None:
            self.created = created
        if file is not None:
            self.file = file
        if size is not None:
            self.size = size
        if md5 is not None:
            self.md5 = md5
        if sha1 is not None:
            self.sha1 = sha1
        if sha224 is not None:
            self.sha224 = sha224
        if sha256 is not None:
            self.sha256 = sha256
        if sha384 is not None:
            self.sha384 = sha384
        if sha512 is not None:
            self.sha512 = sha512
        if upload is not None:
            self.upload = upload

    @property
    def href(self):
        """Gets the href of this Artifact.  # noqa: E501


        :return: The href of this Artifact.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this Artifact.


        :param href: The href of this Artifact.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def created(self):
        """Gets the created of this Artifact.  # noqa: E501

        Timestamp of creation.  # noqa: E501

        :return: The created of this Artifact.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this Artifact.

        Timestamp of creation.  # noqa: E501

        :param created: The created of this Artifact.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def file(self):
        """Gets the file of this Artifact.  # noqa: E501

        The stored file.  # noqa: E501

        :return: The file of this Artifact.  # noqa: E501
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this Artifact.

        The stored file.  # noqa: E501

        :param file: The file of this Artifact.  # noqa: E501
        :type: str
        """

        self._file = file

    @property
    def size(self):
        """Gets the size of this Artifact.  # noqa: E501

        The size of the file in bytes.  # noqa: E501

        :return: The size of this Artifact.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this Artifact.

        The size of the file in bytes.  # noqa: E501

        :param size: The size of this Artifact.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def md5(self):
        """Gets the md5 of this Artifact.  # noqa: E501

        The MD5 checksum of the file if available.  # noqa: E501

        :return: The md5 of this Artifact.  # noqa: E501
        :rtype: str
        """
        return self._md5

    @md5.setter
    def md5(self, md5):
        """Sets the md5 of this Artifact.

        The MD5 checksum of the file if available.  # noqa: E501

        :param md5: The md5 of this Artifact.  # noqa: E501
        :type: str
        """

        self._md5 = md5

    @property
    def sha1(self):
        """Gets the sha1 of this Artifact.  # noqa: E501

        The SHA-1 checksum of the file if available.  # noqa: E501

        :return: The sha1 of this Artifact.  # noqa: E501
        :rtype: str
        """
        return self._sha1

    @sha1.setter
    def sha1(self, sha1):
        """Sets the sha1 of this Artifact.

        The SHA-1 checksum of the file if available.  # noqa: E501

        :param sha1: The sha1 of this Artifact.  # noqa: E501
        :type: str
        """

        self._sha1 = sha1

    @property
    def sha224(self):
        """Gets the sha224 of this Artifact.  # noqa: E501

        The SHA-224 checksum of the file if available.  # noqa: E501

        :return: The sha224 of this Artifact.  # noqa: E501
        :rtype: str
        """
        return self._sha224

    @sha224.setter
    def sha224(self, sha224):
        """Sets the sha224 of this Artifact.

        The SHA-224 checksum of the file if available.  # noqa: E501

        :param sha224: The sha224 of this Artifact.  # noqa: E501
        :type: str
        """

        self._sha224 = sha224

    @property
    def sha256(self):
        """Gets the sha256 of this Artifact.  # noqa: E501

        The SHA-256 checksum of the file if available.  # noqa: E501

        :return: The sha256 of this Artifact.  # noqa: E501
        :rtype: str
        """
        return self._sha256

    @sha256.setter
    def sha256(self, sha256):
        """Sets the sha256 of this Artifact.

        The SHA-256 checksum of the file if available.  # noqa: E501

        :param sha256: The sha256 of this Artifact.  # noqa: E501
        :type: str
        """

        self._sha256 = sha256

    @property
    def sha384(self):
        """Gets the sha384 of this Artifact.  # noqa: E501

        The SHA-384 checksum of the file if available.  # noqa: E501

        :return: The sha384 of this Artifact.  # noqa: E501
        :rtype: str
        """
        return self._sha384

    @sha384.setter
    def sha384(self, sha384):
        """Sets the sha384 of this Artifact.

        The SHA-384 checksum of the file if available.  # noqa: E501

        :param sha384: The sha384 of this Artifact.  # noqa: E501
        :type: str
        """

        self._sha384 = sha384

    @property
    def sha512(self):
        """Gets the sha512 of this Artifact.  # noqa: E501

        The SHA-512 checksum of the file if available.  # noqa: E501

        :return: The sha512 of this Artifact.  # noqa: E501
        :rtype: str
        """
        return self._sha512

    @sha512.setter
    def sha512(self, sha512):
        """Sets the sha512 of this Artifact.

        The SHA-512 checksum of the file if available.  # noqa: E501

        :param sha512: The sha512 of this Artifact.  # noqa: E501
        :type: str
        """

        self._sha512 = sha512

    @property
    def upload(self):
        """Gets the upload of this Artifact.  # noqa: E501


        :return: The upload of this Artifact.  # noqa: E501
        :rtype: str
        """
        return self._upload

    @upload.setter
    def upload(self, upload):
        """Sets the upload of this Artifact.


        :param upload: The upload of this Artifact.  # noqa: E501
        :type: str
        """

        self._upload = upload

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Artifact):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
