# coding: utf-8

"""
    Pulp3 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CertGuard(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'href': 'str',
        'created': 'datetime',
        'type': 'str',
        'name': 'str',
        'description': 'str',
        'ca_certificate': 'str'
    }

    attribute_map = {
        'href': '_href',
        'created': '_created',
        'type': '_type',
        'name': 'name',
        'description': 'description',
        'ca_certificate': 'ca_certificate'
    }

    def __init__(self, href=None, created=None, type=None, name=None, description=None, ca_certificate=None):  # noqa: E501
        """CertGuard - a model defined in Swagger"""  # noqa: E501

        self._href = None
        self._created = None
        self._type = None
        self._name = None
        self._description = None
        self._ca_certificate = None
        self.discriminator = None

        if href is not None:
            self.href = href
        if created is not None:
            self.created = created
        if type is not None:
            self.type = type
        self.name = name
        if description is not None:
            self.description = description
        if ca_certificate is not None:
            self.ca_certificate = ca_certificate

    @property
    def href(self):
        """Gets the href of this CertGuard.  # noqa: E501


        :return: The href of this CertGuard.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this CertGuard.


        :param href: The href of this CertGuard.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def created(self):
        """Gets the created of this CertGuard.  # noqa: E501

        Timestamp of creation.  # noqa: E501

        :return: The created of this CertGuard.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this CertGuard.

        Timestamp of creation.  # noqa: E501

        :param created: The created of this CertGuard.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def type(self):
        """Gets the type of this CertGuard.  # noqa: E501


        :return: The type of this CertGuard.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CertGuard.


        :param type: The type of this CertGuard.  # noqa: E501
        :type: str
        """
        if type is not None and len(type) < 1:
            raise ValueError("Invalid value for `type`, length must be greater than or equal to `1`")  # noqa: E501

        self._type = type

    @property
    def name(self):
        """Gets the name of this CertGuard.  # noqa: E501

        The unique name.  # noqa: E501

        :return: The name of this CertGuard.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CertGuard.

        The unique name.  # noqa: E501

        :param name: The name of this CertGuard.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this CertGuard.  # noqa: E501

        An optional description.  # noqa: E501

        :return: The description of this CertGuard.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CertGuard.

        An optional description.  # noqa: E501

        :param description: The description of this CertGuard.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def ca_certificate(self):
        """Gets the ca_certificate of this CertGuard.  # noqa: E501

        The Certificate Authority (CA) certificate.  # noqa: E501

        :return: The ca_certificate of this CertGuard.  # noqa: E501
        :rtype: str
        """
        return self._ca_certificate

    @ca_certificate.setter
    def ca_certificate(self, ca_certificate):
        """Sets the ca_certificate of this CertGuard.

        The Certificate Authority (CA) certificate.  # noqa: E501

        :param ca_certificate: The ca_certificate of this CertGuard.  # noqa: E501
        :type: str
        """

        self._ca_certificate = ca_certificate

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CertGuard):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
