# coding: utf-8

"""
    Pulp3 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RepositoryVersion(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'href': 'str',
        'created': 'datetime',
        'number': 'int',
        'base_version': 'str',
        'content_summary': 'str'
    }

    attribute_map = {
        'href': '_href',
        'created': '_created',
        'number': 'number',
        'base_version': 'base_version',
        'content_summary': 'content_summary'
    }

    def __init__(self, href=None, created=None, number=None, base_version=None, content_summary=None):  # noqa: E501
        """RepositoryVersion - a model defined in Swagger"""  # noqa: E501

        self._href = None
        self._created = None
        self._number = None
        self._base_version = None
        self._content_summary = None
        self.discriminator = None

        if href is not None:
            self.href = href
        if created is not None:
            self.created = created
        if number is not None:
            self.number = number
        if base_version is not None:
            self.base_version = base_version
        if content_summary is not None:
            self.content_summary = content_summary

    @property
    def href(self):
        """Gets the href of this RepositoryVersion.  # noqa: E501


        :return: The href of this RepositoryVersion.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this RepositoryVersion.


        :param href: The href of this RepositoryVersion.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def created(self):
        """Gets the created of this RepositoryVersion.  # noqa: E501

        Timestamp of creation.  # noqa: E501

        :return: The created of this RepositoryVersion.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this RepositoryVersion.

        Timestamp of creation.  # noqa: E501

        :param created: The created of this RepositoryVersion.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def number(self):
        """Gets the number of this RepositoryVersion.  # noqa: E501


        :return: The number of this RepositoryVersion.  # noqa: E501
        :rtype: int
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this RepositoryVersion.


        :param number: The number of this RepositoryVersion.  # noqa: E501
        :type: int
        """

        self._number = number

    @property
    def base_version(self):
        """Gets the base_version of this RepositoryVersion.  # noqa: E501

        A repository version whose content was used as the initial set of content for this repository version  # noqa: E501

        :return: The base_version of this RepositoryVersion.  # noqa: E501
        :rtype: str
        """
        return self._base_version

    @base_version.setter
    def base_version(self, base_version):
        """Sets the base_version of this RepositoryVersion.

        A repository version whose content was used as the initial set of content for this repository version  # noqa: E501

        :param base_version: The base_version of this RepositoryVersion.  # noqa: E501
        :type: str
        """

        self._base_version = base_version

    @property
    def content_summary(self):
        """Gets the content_summary of this RepositoryVersion.  # noqa: E501

        Various count summaries of the content in the version and the HREF to view them.  # noqa: E501

        :return: The content_summary of this RepositoryVersion.  # noqa: E501
        :rtype: str
        """
        return self._content_summary

    @content_summary.setter
    def content_summary(self, content_summary):
        """Sets the content_summary of this RepositoryVersion.

        Various count summaries of the content in the version and the HREF to view them.  # noqa: E501

        :param content_summary: The content_summary of this RepositoryVersion.  # noqa: E501
        :type: str
        """

        self._content_summary = content_summary

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RepositoryVersion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
