# coding: utf-8

"""
    Pulp3 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RpmRemote(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'href': 'str',
        'created': 'datetime',
        'type': 'str',
        'name': 'str',
        'url': 'str',
        'validate': 'bool',
        'ssl_ca_certificate': 'str',
        'ssl_client_certificate': 'str',
        'ssl_client_key': 'str',
        'ssl_validation': 'bool',
        'proxy_url': 'str',
        'username': 'str',
        'password': 'str',
        'last_updated': 'datetime',
        'download_concurrency': 'int',
        'policy': 'str'
    }

    attribute_map = {
        'href': '_href',
        'created': '_created',
        'type': '_type',
        'name': 'name',
        'url': 'url',
        'validate': 'validate',
        'ssl_ca_certificate': 'ssl_ca_certificate',
        'ssl_client_certificate': 'ssl_client_certificate',
        'ssl_client_key': 'ssl_client_key',
        'ssl_validation': 'ssl_validation',
        'proxy_url': 'proxy_url',
        'username': 'username',
        'password': 'password',
        'last_updated': '_last_updated',
        'download_concurrency': 'download_concurrency',
        'policy': 'policy'
    }

    def __init__(self, href=None, created=None, type=None, name=None, url=None, validate=None, ssl_ca_certificate=None, ssl_client_certificate=None, ssl_client_key=None, ssl_validation=None, proxy_url=None, username=None, password=None, last_updated=None, download_concurrency=None, policy='immediate'):  # noqa: E501
        """RpmRemote - a model defined in Swagger"""  # noqa: E501

        self._href = None
        self._created = None
        self._type = None
        self._name = None
        self._url = None
        self._validate = None
        self._ssl_ca_certificate = None
        self._ssl_client_certificate = None
        self._ssl_client_key = None
        self._ssl_validation = None
        self._proxy_url = None
        self._username = None
        self._password = None
        self._last_updated = None
        self._download_concurrency = None
        self._policy = None
        self.discriminator = None

        if href is not None:
            self.href = href
        if created is not None:
            self.created = created
        if type is not None:
            self.type = type
        self.name = name
        self.url = url
        if validate is not None:
            self.validate = validate
        if ssl_ca_certificate is not None:
            self.ssl_ca_certificate = ssl_ca_certificate
        if ssl_client_certificate is not None:
            self.ssl_client_certificate = ssl_client_certificate
        if ssl_client_key is not None:
            self.ssl_client_key = ssl_client_key
        if ssl_validation is not None:
            self.ssl_validation = ssl_validation
        if proxy_url is not None:
            self.proxy_url = proxy_url
        if username is not None:
            self.username = username
        if password is not None:
            self.password = password
        if last_updated is not None:
            self.last_updated = last_updated
        if download_concurrency is not None:
            self.download_concurrency = download_concurrency
        if policy is not None:
            self.policy = policy

    @property
    def href(self):
        """Gets the href of this RpmRemote.  # noqa: E501


        :return: The href of this RpmRemote.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this RpmRemote.


        :param href: The href of this RpmRemote.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def created(self):
        """Gets the created of this RpmRemote.  # noqa: E501

        Timestamp of creation.  # noqa: E501

        :return: The created of this RpmRemote.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this RpmRemote.

        Timestamp of creation.  # noqa: E501

        :param created: The created of this RpmRemote.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def type(self):
        """Gets the type of this RpmRemote.  # noqa: E501


        :return: The type of this RpmRemote.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this RpmRemote.


        :param type: The type of this RpmRemote.  # noqa: E501
        :type: str
        """
        if type is not None and len(type) < 1:
            raise ValueError("Invalid value for `type`, length must be greater than or equal to `1`")  # noqa: E501

        self._type = type

    @property
    def name(self):
        """Gets the name of this RpmRemote.  # noqa: E501

        A unique name for this remote.  # noqa: E501

        :return: The name of this RpmRemote.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RpmRemote.

        A unique name for this remote.  # noqa: E501

        :param name: The name of this RpmRemote.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def url(self):
        """Gets the url of this RpmRemote.  # noqa: E501

        The URL of an external content source.  # noqa: E501

        :return: The url of this RpmRemote.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this RpmRemote.

        The URL of an external content source.  # noqa: E501

        :param url: The url of this RpmRemote.  # noqa: E501
        :type: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501
        if url is not None and len(url) < 1:
            raise ValueError("Invalid value for `url`, length must be greater than or equal to `1`")  # noqa: E501

        self._url = url

    @property
    def validate(self):
        """Gets the validate of this RpmRemote.  # noqa: E501

        If True, the plugin will validate imported artifacts.  # noqa: E501

        :return: The validate of this RpmRemote.  # noqa: E501
        :rtype: bool
        """
        return self._validate

    @validate.setter
    def validate(self, validate):
        """Sets the validate of this RpmRemote.

        If True, the plugin will validate imported artifacts.  # noqa: E501

        :param validate: The validate of this RpmRemote.  # noqa: E501
        :type: bool
        """

        self._validate = validate

    @property
    def ssl_ca_certificate(self):
        """Gets the ssl_ca_certificate of this RpmRemote.  # noqa: E501

        A PEM encoded CA certificate used to validate the server certificate presented by the remote server.  # noqa: E501

        :return: The ssl_ca_certificate of this RpmRemote.  # noqa: E501
        :rtype: str
        """
        return self._ssl_ca_certificate

    @ssl_ca_certificate.setter
    def ssl_ca_certificate(self, ssl_ca_certificate):
        """Sets the ssl_ca_certificate of this RpmRemote.

        A PEM encoded CA certificate used to validate the server certificate presented by the remote server.  # noqa: E501

        :param ssl_ca_certificate: The ssl_ca_certificate of this RpmRemote.  # noqa: E501
        :type: str
        """

        self._ssl_ca_certificate = ssl_ca_certificate

    @property
    def ssl_client_certificate(self):
        """Gets the ssl_client_certificate of this RpmRemote.  # noqa: E501

        A PEM encoded client certificate used for authentication.  # noqa: E501

        :return: The ssl_client_certificate of this RpmRemote.  # noqa: E501
        :rtype: str
        """
        return self._ssl_client_certificate

    @ssl_client_certificate.setter
    def ssl_client_certificate(self, ssl_client_certificate):
        """Sets the ssl_client_certificate of this RpmRemote.

        A PEM encoded client certificate used for authentication.  # noqa: E501

        :param ssl_client_certificate: The ssl_client_certificate of this RpmRemote.  # noqa: E501
        :type: str
        """

        self._ssl_client_certificate = ssl_client_certificate

    @property
    def ssl_client_key(self):
        """Gets the ssl_client_key of this RpmRemote.  # noqa: E501

        A PEM encoded private key used for authentication.  # noqa: E501

        :return: The ssl_client_key of this RpmRemote.  # noqa: E501
        :rtype: str
        """
        return self._ssl_client_key

    @ssl_client_key.setter
    def ssl_client_key(self, ssl_client_key):
        """Sets the ssl_client_key of this RpmRemote.

        A PEM encoded private key used for authentication.  # noqa: E501

        :param ssl_client_key: The ssl_client_key of this RpmRemote.  # noqa: E501
        :type: str
        """

        self._ssl_client_key = ssl_client_key

    @property
    def ssl_validation(self):
        """Gets the ssl_validation of this RpmRemote.  # noqa: E501

        If True, SSL peer validation must be performed.  # noqa: E501

        :return: The ssl_validation of this RpmRemote.  # noqa: E501
        :rtype: bool
        """
        return self._ssl_validation

    @ssl_validation.setter
    def ssl_validation(self, ssl_validation):
        """Sets the ssl_validation of this RpmRemote.

        If True, SSL peer validation must be performed.  # noqa: E501

        :param ssl_validation: The ssl_validation of this RpmRemote.  # noqa: E501
        :type: bool
        """

        self._ssl_validation = ssl_validation

    @property
    def proxy_url(self):
        """Gets the proxy_url of this RpmRemote.  # noqa: E501

        The proxy URL. Format: scheme://user:password@host:port  # noqa: E501

        :return: The proxy_url of this RpmRemote.  # noqa: E501
        :rtype: str
        """
        return self._proxy_url

    @proxy_url.setter
    def proxy_url(self, proxy_url):
        """Sets the proxy_url of this RpmRemote.

        The proxy URL. Format: scheme://user:password@host:port  # noqa: E501

        :param proxy_url: The proxy_url of this RpmRemote.  # noqa: E501
        :type: str
        """

        self._proxy_url = proxy_url

    @property
    def username(self):
        """Gets the username of this RpmRemote.  # noqa: E501

        The username to be used for authentication when syncing.  # noqa: E501

        :return: The username of this RpmRemote.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this RpmRemote.

        The username to be used for authentication when syncing.  # noqa: E501

        :param username: The username of this RpmRemote.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def password(self):
        """Gets the password of this RpmRemote.  # noqa: E501

        The password to be used for authentication when syncing.  # noqa: E501

        :return: The password of this RpmRemote.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this RpmRemote.

        The password to be used for authentication when syncing.  # noqa: E501

        :param password: The password of this RpmRemote.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def last_updated(self):
        """Gets the last_updated of this RpmRemote.  # noqa: E501

        Timestamp of the most recent update of the remote.  # noqa: E501

        :return: The last_updated of this RpmRemote.  # noqa: E501
        :rtype: datetime
        """
        return self._last_updated

    @last_updated.setter
    def last_updated(self, last_updated):
        """Sets the last_updated of this RpmRemote.

        Timestamp of the most recent update of the remote.  # noqa: E501

        :param last_updated: The last_updated of this RpmRemote.  # noqa: E501
        :type: datetime
        """

        self._last_updated = last_updated

    @property
    def download_concurrency(self):
        """Gets the download_concurrency of this RpmRemote.  # noqa: E501

        Total number of simultaneous connections.  # noqa: E501

        :return: The download_concurrency of this RpmRemote.  # noqa: E501
        :rtype: int
        """
        return self._download_concurrency

    @download_concurrency.setter
    def download_concurrency(self, download_concurrency):
        """Sets the download_concurrency of this RpmRemote.

        Total number of simultaneous connections.  # noqa: E501

        :param download_concurrency: The download_concurrency of this RpmRemote.  # noqa: E501
        :type: int
        """
        if download_concurrency is not None and download_concurrency < 1:  # noqa: E501
            raise ValueError("Invalid value for `download_concurrency`, must be a value greater than or equal to `1`")  # noqa: E501

        self._download_concurrency = download_concurrency

    @property
    def policy(self):
        """Gets the policy of this RpmRemote.  # noqa: E501

        The policy to use when downloading content. The possible values include: 'immediate', 'on_demand', and 'cache_only'. 'immediate' is the default.  # noqa: E501

        :return: The policy of this RpmRemote.  # noqa: E501
        :rtype: str
        """
        return self._policy

    @policy.setter
    def policy(self, policy):
        """Sets the policy of this RpmRemote.

        The policy to use when downloading content. The possible values include: 'immediate', 'on_demand', and 'cache_only'. 'immediate' is the default.  # noqa: E501

        :param policy: The policy of this RpmRemote.  # noqa: E501
        :type: str
        """
        allowed_values = ["immediate", "on_demand", "streamed"]  # noqa: E501
        if policy not in allowed_values:
            raise ValueError(
                "Invalid value for `policy` ({0}), must be one of {1}"  # noqa: E501
                .format(policy, allowed_values)
            )

        self._policy = policy

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RpmRemote):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
